In [1]:
import torch
import numpy as np

### check GPU available


In [94]:
device = torch.device("cuda") if torch.cuda.is_available() else "cpu"
print(device)

cuda


### create tensor with custom value

In [9]:
a = torch.tensor([1, 2, 3, 4], dtype=torch.float64, device=device)
b = torch.tensor([4, 5, 6, 7], dtype=torch.float64, device=device)
print(a)
print(a.size())
print(b)
print(b.size())

tensor([1., 2., 3., 4.], device='cuda:0', dtype=torch.float64)
torch.Size([4])
tensor([4., 5., 6., 7.], device='cuda:0', dtype=torch.float64)
torch.Size([4])


### create random tensor

In [25]:
a = torch.rand(4, 4, dtype=torch.float64, device=device)
print(a)

tensor([[0.3562, 0.9924, 0.5074, 0.2461],
        [0.7582, 0.8656, 0.5525, 0.6764],
        [0.4090, 0.8085, 0.8548, 0.3139],
        [0.2251, 0.2642, 0.3328, 0.9133]], device='cuda:0',
       dtype=torch.float64)


### zeros tensor

In [26]:
a = torch.zeros(4, 4, dtype=torch.float64, device=device)
print(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)


### ones tensor

In [27]:
a = torch.ones(4, 4, dtype=torch.float, device=device)
print(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')


### reshape tensor

In [32]:
a = torch.rand(4, 4, dtype=torch.float64, device=device)
b = torch.reshape(a, (2, 8))
c = a.view(2, 8)
print(a.size())
print(b.size())
print(c.size())

torch.Size([4, 4])
torch.Size([2, 8])
torch.Size([2, 8])


### Add operation

In [88]:
a = torch.tensor([1, 2, 3], device=device)
b = torch.tensor([4, 5, 6], device=device)

# add
c1 = torch.add(a, b)
c2 = a + b
c3 = a.add_(b)
print(c1)
print(c2)
print(c3)
print()

tensor([5, 7, 9], device='cuda:0')
tensor([5, 7, 9], device='cuda:0')
tensor([5, 7, 9], device='cuda:0')



### Subtract operation

In [93]:
a = torch.tensor([1, 2, 3], device=device)
b = torch.tensor([4, 5, 6], device=device)

c4 = torch.subtract(a, b)
c5 = a - b
c6 = a.sub_(b)

print(c4)
print(c5)
print(c6)
print()

tensor([-3, -3, -3], device='cuda:0')
tensor([-3, -3, -3], device='cuda:0')
tensor([-3, -3, -3], device='cuda:0')



### Multiply operation

In [92]:
a = torch.tensor([1, 2, 3], device=device)
b = torch.tensor([4, 5, 6], device=device)

c7 = torch.mul(a, b)
c8 = a * b
c9 = a.mul_(b)
print(c7)
print(c8)
print(c9)


tensor([ 4, 10, 18], device='cuda:0')
tensor([ 4, 10, 18], device='cuda:0')
tensor([ 4, 10, 18], device='cuda:0')


## Autograd

## gradeint computation

In [97]:
x = torch.randn(4, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
print(z)

r = z.mean()
print(r)

r.backward() # dz/dx
print(x.grad)



tensor([-0.4384,  2.3224, -1.3642,  1.9052], requires_grad=True)
tensor([1.5616, 4.3224, 0.6358, 3.9052], grad_fn=<AddBackward0>)
tensor([ 4.8773, 37.3656,  0.8085, 30.5014], grad_fn=<MulBackward0>)
tensor(18.3882, grad_fn=<MeanBackward0>)
tensor([1.5616, 4.3224, 0.6358, 3.9052])
tensor([-0.4384,  2.3224, -1.3642,  1.9052])
